name: Build APK (Final Fixed)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build inside container
        run: |
          docker run --rm \
            --entrypoint /bin/bash \
            -v ${{ github.workspace }}:/home/user/hostcwd \
            -w /home/user/hostcwd \
            kivy/buildozer \
            -c "
              yes | sdkmanager --licenses > /dev/null 2>&1 || true
              sdkmanager 'build-tools;33.0.2'
              rm -rf /home/user/.buildozer/android/platform/android-sdk/build-tools/37*
              buildozer android debug
            "

      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
          
